export const DefaultTheme = {
  colors: {
    white: "#FFF",
    error100: "#FFD1C9",
    // header: "#DFE9FE",
    background: "#FFFFFF",
    black: "#072340",
    primary: "#FC7960",
    borderGrey: "#A4B0BF",
    lightBlue: "#DFE9FE",
    lightGrey: "#F6F6F6",
    inactive: "#E4E6EC",
    // background: "#FCFCFC",
    // black: "#182E1E",
    // primary: "#F68964",
    // borderGrey: "#D6D9D4",
    // lightBlue: "#ADC993",
    // lightGrey: "#F0F3ED",
    // inactive: "#DCE6D4",
  },
  fontFamily: {
    regularHeaders: "Georgia",
    boldHeaders: "GeorgiaBold",
  },
};
